FORMAT: 1A
HOST: https://private-32e54a-attendancetrackermockdata.apiary-mock.com/

# Attendance Tracker Mock Data

Attendance Tracker Mock Data is an API with purpose of serving a mocked data for a simple Android front end.

## Service Collections [/services]

### List All Services [GET]

+ Response 200 (application/json)

        {
            "data": [
                        {
                            "name": "leave tracker",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/deadline.png"
                        },
                        {
                            "name": "time tracker",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/alarm-clock.png"
                        },
                        {
                            "name": "attendance",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/calendar.png"
                        },
                        {
                            "name": "files",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/folder.png"
                        },
                        {
                            "name": "organization",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/collaboration.png"
                        },
                        {
                            "name": "announcements",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/bullhorn.png"
                        },
                        {
                            "name": "presentations",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/presentation-2.png"
                        },
                        {
                            "name": "flight",
                            "icon": "https://raw.githubusercontent.com/khrlimam/static-mock-data/master/airplane.png"
                        }
                    ]
        }


## Feeds Collections [/feeds]

### List Feeds [GET]

+ Response 200 (application/json)

        {
            "data": [
                {
                    "date": "2019-10-19 02:32:07",
                    "name": "Alexandra Holt",
                    "present": false,
                    "reason": "sick"
                },
                {
                    "date": "2019-10-17 06:57:31",
                    "name": "Lisa Higgins",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 06:22:59",
                    "name": "Sarah Thomas",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 20:30:03",
                    "name": "John Gregory",
                    "present": true,
                    "reason": "good"
                },
                {
                    "date": "2019-10-16 17:25:38",
                    "name": "Brandon Perez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 09:18:39",
                    "name": "Jennifer Simmons",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 17:34:34",
                    "name": "Mario Nelson",
                    "present": true,
                    "reason": "good"
                },
                {
                    "date": "2019-10-04 13:58:27",
                    "name": "Karen Smith",
                    "present": false,
                    "reason": "have urgent situation"
                },
                {
                    "date": "2019-10-11 18:26:18",
                    "name": "Jerry Scott",
                    "present": true,
                    "reason": "present"
                },
                {
                    "date": "2019-10-02 14:41:15",
                    "name": "Jennifer Mendoza",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 08:43:15",
                    "name": "Philip Ortega",
                    "present": true,
                    "reason": "present"
                },
                {
                    "date": "2019-10-05 14:03:50",
                    "name": "Michael Thompson",
                    "present": false,
                    "reason": "have urgent situation"
                },
                {
                    "date": "2019-10-15 12:16:27",
                    "name": "Alexander Bennett",
                    "present": false,
                    "reason": "sick"
                },
                {
                    "date": "2019-10-05 07:52:38",
                    "name": "Michael Mullins",
                    "present": true,
                    "reason": "good"
                },
                {
                    "date": "2019-10-13 20:05:13",
                    "name": "Miguel Oneill",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 05:48:50",
                    "name": "Christopher Taylor",
                    "present": false,
                    "reason": "sick"
                },
                {
                    "date": "2019-10-10 04:07:12",
                    "name": "Christian Foley",
                    "present": true,
                    "reason": "present"
                },
                {
                    "date": "2019-10-14 13:56:09",
                    "name": "Mrs. Sandra Ferguson",
                    "present": true,
                    "reason": "good"
                },
                {
                    "date": "2019-10-20 00:29:10",
                    "name": "Sherry Myers",
                    "present": false,
                    "reason": "have urgent situation"
                },
                {
                    "date": "2019-10-12 21:36:04",
                    "name": "Michelle Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 00:49:27",
                    "name": "Elizabeth Anderson",
                    "present": false,
                    "reason": "sick"
                },
                {
                    "date": "2019-10-08 23:19:09",
                    "name": "Mark Foster",
                    "present": true,
                    "reason": "present"
                },
                {
                    "date": "2019-10-03 09:27:55",
                    "name": "Vincent Pearson",
                    "present": true,
                    "reason": "good"
                },
                {
                    "date": "2019-10-11 23:13:51",
                    "name": "Nicole Wade",
                    "present": false,
                    "reason": "have urgent situation"
                },
                {
                    "date": "2019-10-03 08:29:12",
                    "name": "Cynthia Bautista",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 22:46:28",
                    "name": "Gregory Summers",
                    "present": false,
                    "reason": "sick"
                },
                {
                    "date": "2019-10-12 13:02:55",
                    "name": "Anthony Mason",
                    "present": true,
                    "reason": "present"
                },
                {
                    "date": "2019-10-05 13:35:11",
                    "name": "Jaclyn Randall",
                    "present": true,
                    "reason": "good"
                },
                {
                    "date": "2019-10-04 08:35:05",
                    "name": "Brandon Nelson",
                    "present": false,
                    "reason": "have urgent situation"
                },
                {
                    "date": "2019-10-15 09:38:05",
                    "name": "Donald Velazquez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 07:54:46",
                    "name": "Cheyenne Rivera",
                    "present": false,
                    "reason": "sick"
                },
                {
                    "date": "2019-10-12 03:26:45",
                    "name": "Tiffany Carter",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 16:03:51",
                    "name": "Cesar Conway",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 16:07:18",
                    "name": "Jacob Dodson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 23:31:40",
                    "name": "Patrick Johnson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 23:42:49",
                    "name": "Michelle Dougherty",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 04:37:19",
                    "name": "Justin Harris",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 14:31:02",
                    "name": "Heather Ramsey",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 14:54:07",
                    "name": "Chelsea Lin",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-10 11:24:11",
                    "name": "Jennifer Brown",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 20:21:34",
                    "name": "Erin Butler",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 12:10:17",
                    "name": "Joshua Saunders",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 23:38:34",
                    "name": "Jared Barrett",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 05:01:20",
                    "name": "Billy Velazquez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 14:26:14",
                    "name": "Julia Vance",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 01:48:42",
                    "name": "Jessica Foster",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 04:52:27",
                    "name": "Sarah Vazquez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 20:03:36",
                    "name": "Daniel Thompson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 19:19:06",
                    "name": "Michael Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-09 01:37:23",
                    "name": "Christopher Banks",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 10:17:32",
                    "name": "Virginia Simmons",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 11:30:06",
                    "name": "Jon Ramos",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 12:20:30",
                    "name": "John Rios",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 21:53:15",
                    "name": "Justin Moreno",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 19:16:12",
                    "name": "William Lawrence",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 23:24:54",
                    "name": "Lauren Clarke",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 07:12:00",
                    "name": "Joseph Campbell",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 19:37:20",
                    "name": "Hannah Blair DVM",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 14:27:44",
                    "name": "Carla Hutchinson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 16:23:21",
                    "name": "Spencer Jones",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 13:22:02",
                    "name": "Dr. Christopher Robertson II",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 12:03:00",
                    "name": "Robert Palmer",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 14:11:56",
                    "name": "Brian Knight",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 19:10:53",
                    "name": "Christine Johnson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 17:27:34",
                    "name": "Alexander Blankenship",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 04:54:40",
                    "name": "Kylie Herrera",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 21:42:40",
                    "name": "Danny Mason",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 01:47:36",
                    "name": "Stephen Lamb",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 01:49:43",
                    "name": "Zachary Cameron",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 05:44:54",
                    "name": "Samantha White",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 21:34:22",
                    "name": "Cameron Davis",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 23:00:17",
                    "name": "Carolyn Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-09 20:04:02",
                    "name": "David Jones",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 16:13:27",
                    "name": "Amanda Washington MD",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 20:07:20",
                    "name": "Cindy Conner",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 22:52:34",
                    "name": "Diane Rodriguez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 07:57:15",
                    "name": "Jason Phelps",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 05:45:34",
                    "name": "Alyssa Horton",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 21:50:02",
                    "name": "Sara Elliott",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-12 04:09:34",
                    "name": "Lisa Oconnor",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 11:47:35",
                    "name": "Richard Hernandez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-19 14:49:58",
                    "name": "Dale Jones",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-09 03:17:33",
                    "name": "Adam Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 05:44:00",
                    "name": "James Carter",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 11:14:01",
                    "name": "Erin Horne",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 15:31:53",
                    "name": "Jessica Conrad",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 06:28:00",
                    "name": "Mason Edwards",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 12:40:18",
                    "name": "Julia Moore",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 14:17:33",
                    "name": "Teresa Johnston",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 14:53:21",
                    "name": "Joshua Blair",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 22:23:19",
                    "name": "Brianna Williams",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-10 12:13:01",
                    "name": "Bridget Murphy",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 00:43:49",
                    "name": "Lori Sanchez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 15:42:30",
                    "name": "Jim Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-12 06:30:01",
                    "name": "Jennifer Reed",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-09 02:38:41",
                    "name": "Tammy Miller",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 10:46:03",
                    "name": "Melissa Ortiz",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-20 02:09:36",
                    "name": "Kimberly Chung",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 05:45:47",
                    "name": "Gary Flynn",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-19 15:57:06",
                    "name": "Timothy Buchanan",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 08:45:15",
                    "name": "Tyler Grimes",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 20:14:09",
                    "name": "Ian Sanchez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 22:57:06",
                    "name": "Brian Hernandez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 08:42:36",
                    "name": "Desiree Snyder",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 06:50:22",
                    "name": "Tristan Chapman",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 17:03:19",
                    "name": "Robert Mcpherson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-12 13:27:44",
                    "name": "Jeffrey Moon",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 17:28:56",
                    "name": "Nancy Harper",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 04:46:00",
                    "name": "Wendy Thompson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 12:07:35",
                    "name": "Jacob Kelley",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 20:38:58",
                    "name": "Meagan Roth",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 13:57:01",
                    "name": "Kathryn Harris",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-09 18:14:59",
                    "name": "Kara Willis",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-10 10:41:04",
                    "name": "Grace Fernandez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-10 15:52:56",
                    "name": "Nicole Solis",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 07:10:09",
                    "name": "Jackson Anderson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 15:52:00",
                    "name": "Garrett Shannon",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 00:13:56",
                    "name": "Evan Deleon",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-12 18:49:45",
                    "name": "Patrick Carter",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-10 07:16:35",
                    "name": "Nathan Marshall",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 10:25:10",
                    "name": "Amber Martinez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 22:54:42",
                    "name": "Meagan Evans",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-12 14:00:02",
                    "name": "Vincent Ortiz",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 02:04:57",
                    "name": "Lauren Castaneda",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 19:17:53",
                    "name": "Adam Nunez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 09:45:44",
                    "name": "Eric Logan",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 00:37:50",
                    "name": "Elizabeth Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 02:42:41",
                    "name": "Ryan Vasquez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 18:56:03",
                    "name": "Carolyn Rowe",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 22:38:50",
                    "name": "Robert Smith",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 05:59:04",
                    "name": "Daniel Green",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 00:39:06",
                    "name": "Abigail Brown",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-12 15:46:22",
                    "name": "Ashley Stephens",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 07:17:28",
                    "name": "Alexis Williams",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 20:01:39",
                    "name": "Heidi Rogers",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-18 05:33:00",
                    "name": "Kaitlyn Ruiz",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 13:48:14",
                    "name": "Ryan Beck",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 13:31:12",
                    "name": "Cameron Bass",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 15:06:55",
                    "name": "Rebecca Miller",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 14:22:35",
                    "name": "Maria Carrillo",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-19 13:28:34",
                    "name": "Rachel Watson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 08:29:04",
                    "name": "Daniel Garrett",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-09 06:27:02",
                    "name": "Christopher Santos",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 14:11:06",
                    "name": "Jessica Chan",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 06:47:34",
                    "name": "Derek Gonzales",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 00:25:36",
                    "name": "James Evans",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 20:24:22",
                    "name": "Tyler Jensen",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-19 04:19:24",
                    "name": "Daniel Sutton",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 19:17:08",
                    "name": "Terry Mccarty",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 11:51:33",
                    "name": "Johnny Trujillo",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 14:35:46",
                    "name": "Nicole King",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 08:42:49",
                    "name": "Danny Cain",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 20:50:09",
                    "name": "Julie Espinoza",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 15:39:20",
                    "name": "Kimberly Acosta",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-19 04:49:06",
                    "name": "Leonard Mitchell",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 21:37:19",
                    "name": "Michele Dixon",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 02:31:07",
                    "name": "Carolyn Williams",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-19 21:40:44",
                    "name": "James Valenzuela",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 08:06:10",
                    "name": "Judith Howell",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 09:38:44",
                    "name": "Robin Greene",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 15:23:11",
                    "name": "Joanna Rios DVM",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 00:55:07",
                    "name": "Laura Garrison",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 13:20:24",
                    "name": "Bradley Stewart",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 05:21:14",
                    "name": "William Gould",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 08:53:11",
                    "name": "Mr. Malik Reyes",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 02:26:26",
                    "name": "Julie Ortega",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 21:12:57",
                    "name": "Eric Nelson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 20:21:09",
                    "name": "Elizabeth Zamora",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 06:55:55",
                    "name": "Brandon Vargas",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 16:34:59",
                    "name": "Brent Zamora",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-14 05:52:48",
                    "name": "Lisa Powell",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 17:18:53",
                    "name": "Christina Tucker",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 13:44:27",
                    "name": "Donna Johnson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 14:00:44",
                    "name": "Eric Brown",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 06:04:31",
                    "name": "Crystal Hays",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 00:59:44",
                    "name": "Tanya Hancock",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-10 18:31:49",
                    "name": "Julie Dickerson DVM",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 00:21:02",
                    "name": "Jill Johnson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 23:26:45",
                    "name": "Bailey Lopez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 04:04:33",
                    "name": "Sandra Medina",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 13:04:26",
                    "name": "Eddie Jones",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 21:49:53",
                    "name": "Victoria Jones",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 05:36:21",
                    "name": "Thomas Chapman",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 10:33:55",
                    "name": "Amanda Callahan",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 00:42:23",
                    "name": "William Harrison",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-11 12:08:41",
                    "name": "Mr. Keith Clements",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-02 05:22:50",
                    "name": "Roberto Thompson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-08 11:35:54",
                    "name": "Karl Burns",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-06 22:17:18",
                    "name": "Sarah Martinez",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 13:05:10",
                    "name": "Kristen Vargas",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-03 07:18:21",
                    "name": "Pamela Wise",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-13 10:13:48",
                    "name": "Melissa Wilson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-05 02:01:19",
                    "name": "Allen Keller",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-15 19:15:25",
                    "name": "Susan Henderson",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-01 13:43:30",
                    "name": "Andrew Guzman",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-07 02:05:27",
                    "name": "Christina Rivera",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-16 17:06:43",
                    "name": "Rebecca Wu DDS",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-04 05:20:36",
                    "name": "Dennis Jones",
                    "present": false,
                    "reason": "not feeling well"
                },
                {
                    "date": "2019-10-17 00:46:12",
                    "name": "John Klein",
                    "present": false,
                    "reason": "not feeling well"
                }
            ]
        }


## User Approval Collections [/user/{username}/approval{?status}]

### Show User Approval With Given Parameters
+ Parameters
    + username (string, required, `khairulimam`) - Username which approval to see by ?status
    + status (string, optional, `pending`) - Specify which approval status to see [pending, approved, rejected]. The default is pending
        

## User Approval Collections [/user/{username}/approval?status=pending]

### Show User Approval With Status Pending [GET]
+ Parameters
    + username (string, required) - Username which approval to see by ?status

+ Response 200 (application/json)

        {
            "data": []
        }
        
        
## User Approval Collections [/user/{username}/approval?status=approved]
        
### Show User Approval With Status Approved [GET]
+ Parameters
    + username (string, required) - Username which approval to see by ?status

+ Response 200 (application/json)
        
        
        {
            "data": [
                        {
                            "date": "2019-10-02 05:10:10",
                            "present": false,
                            "reason": "sick"
                        },
                        {
                            "date": "2019-10-03 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-04 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-05 05:10:10",
                            "present": true,
                            "reason": "good"
                        },
                        {
                            "date": "2019-10-06 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-07 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-08 05:10:10",
                            "present": true,
                            "reason": "good"
                        },
                        {
                            "date": "2019-10-09 05:10:10",
                            "present": false,
                            "reason": "have urgent situation"
                        },
                        {
                            "date": "2019-10-10 05:10:10",
                            "present": true,
                            "reason": "present"
                        },
                        {
                            "date": "2019-10-11 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-12 05:10:10",
                            "present": true,
                            "reason": "present"
                        },
                        {
                            "date": "2019-10-13 05:10:10",
                            "present": false,
                            "reason": "have urgent situation"
                        },
                        {
                            "date": "2019-10-14 05:10:10",
                            "present": false,
                            "reason": "sick"
                        },
                        {
                            "date": "2019-10-15 05:10:10",
                            "present": true,
                            "reason": "good"
                        },
                        {
                            "date": "2019-10-16 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-17 05:10:10",
                            "present": false,
                            "reason": "sick"
                        },
                        {
                            "date": "2019-10-18 05:10:10",
                            "present": true,
                            "reason": "present"
                        },
                        {
                            "date": "2019-10-19 05:10:10",
                            "present": true,
                            "reason": "good"
                        },
                        {
                            "date": "2019-10-20 05:10:10",
                            "present": false,
                            "reason": "have urgent situation"
                        },
                        {
                            "date": "2019-10-21 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-22 05:10:10",
                            "present": false,
                            "reason": "sick"
                        },
                        {
                            "date": "2019-10-23 05:10:10",
                            "present": true,
                            "reason": "present"
                        },
                        {
                            "date": "2019-10-24 05:10:10",
                            "present": true,
                            "reason": "good"
                        },
                        {
                            "date": "2019-10-25 05:10:10",
                            "present": false,
                            "reason": "have urgent situation"
                        },
                        {
                            "date": "2019-10-26 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        },
                        {
                            "date": "2019-10-27 05:10:10",
                            "present": false,
                            "reason": "sick"
                        },
                        {
                            "date": "2019-10-28 05:10:10",
                            "present": true,
                            "reason": "present"
                        },
                        {
                            "date": "2019-10-29 05:10:10",
                            "present": true,
                            "reason": "good"
                        },
                        {
                            "date": "2019-10-30 05:10:10",
                            "present": false,
                            "reason": "have urgent situation"
                        },
                        {
                            "date": "2019-10-31 05:10:10",
                            "present": false,
                            "reason": "not feeling well"
                        }
                    ]
        }
    

## User Approval Collections [/user/{username}/approval?status=rejected]

### Show User Approval With Status Rejected [GET]
+ Parameters
    + username (string, required) - Username which approval to see by ?status

+ Response 200 (application/json)

        {
            "data": []
        }